# Generated by Django 3.2 on 2021-05-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210510_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='renew',
            field=models.TextField(null=True),
        ),
    ]
