# Generated by Django 3.2 on 2021-05-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_profile_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='llt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
