# Generated by Django 3.2 on 2021-05-11 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_auto_20210511_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_topic', models.TextField(null=True)),
                ('m_type', models.BigIntegerField(null=True)),
                ('m_date', models.CharField(max_length=28, null=True)),
                ('m_creation', models.DateField(null=True)),
                ('m_length', models.CharField(max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('m_id', 'user')},
            },
        ),
    ]
