# Generated by Django 3.2 on 2021-05-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_meeting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set(),
        ),
    ]
