# Generated by Django 3.2 on 2021-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_meeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zoom_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
