# Generated by Django 3.2 on 2021-05-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_meeting_m_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_report',
            field=models.BooleanField(default=True),
        ),
    ]
