# Generated by Django 3.2 on 2021-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_meeting_is_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
